# TODO: Is this needed if separated?
coordinator:
  # Address for M3Coordinator to listen for traffic.
  listenAddress: <url>

  # Configuration for logging.
  logging:
    # Log file location
    file: <string>
    # Error logging level
    level: <string>
    # TODO: ??
    fields:

  metrics:
    scope:
      prefix: "coordinator"
    prometheus:
      handlerPath: /metrics
      listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
    sanitization: prometheus
    samplingRate: 1.0
    # Enable Go runtime metrics, valid options: [none, simple, moderate, detailed]
    # See https://github.com/m3db/m3/blob/master/src/x/instrument/extended.go#L39:L64 for more details
    extended: <string>
    
  tagOptions:
    idScheme: quoted